baseURL = "https://re-collection.netlify.app/"
languageCode = "en-us"
title = "re-collection - Photo Archive"
theme = "ananke"

[params]
  description = "A personal archive of film scans and photography"
  author = "Thornado007"
  
# Enable Netlify CMS
[mediaTypes]
  [mediaTypes."text/netlify"]
    suffix = "html"

[outputFormats]
  [outputFormats."NETLIFY"]
    mediaType = "text/netlify"
    baseName = "index"
    isPlainText = true

[outputs]
  home = ["HTML", "NETLIFY"]
