backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "archive"
    label: "Archive Items"
    folder: "content/archive"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Body"
        name: "body"
        widget: "markdown"
